apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: prorickey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: prorickeyregcred
      containers:
        - name: portfolio
          image: docker.prorickey.xyz/prorickey/nextjs-portfolio:0.1.2
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: prorickey
spec:
  selector:
    app: portfolio
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer